# (summary)Lab-1_Basic_ML

## Lab01-Tensor_Manipulation

### 1. 1D, 2D Array with pytorch

In [4]:
"""
"define 1D, 2D"
1D == [], 2D+ == ()

"torch.Tensor == torch.FloatTensor"
torch.Tensor([1, 2]) == [1, 2]
torch.Tensor([[1, 2]]) == (1, 2)
torch.Tensor([[1], [2]]) == (1,
                             2)
torth.Tensor([[1, 2, 3],  ==  (1, 2, 3,
              [4, 5, 6]])      4, 5, 6)

"tensor.dim(), tensor.size()"
t.dim() == dimension(1D == 1, 2D == 2, 3D == 3, ...)
t.size() == t.shape == size of tensor(1D == [3], 2D == [1, 3], 3D == [1, 1, 3], ...)
"""

# 1D Array with Pytorch
import torch
t = torch.Tensor([1, 2, 3]) # [1, 2, 3]
print(t.dim()) # t.dim() == 1 
print(t.size()) # t.size() == [3]

# 2D Array with pytorch
t = torch.Tensor([[1, 2, 3],
                  [4, 5, 6]])
print(t.dim()) # t.dim() == 2
print(t.size()) # t.size() == [2, 3]

1
torch.Size([3])
2
torch.Size([2, 3])


### 2. Broadcasting

In [3]:
"""
m1 = (1, 2), m2 = (3,
                   4)

m1 + m2 == (1, 2  +  (3, 3  == (4, 5
            1, 2)     4, 4)     5, 6)

"element wise multiplication"
m1 * m2 == (1, 2  *  (3, 3  == (3, 6
            1, 2)     4, 4)     4, 8)

"matrix multiplication"
m1.matmul(m2) == 11
"""
import torch
m1 = torch.Tensor([[1, 2]]) # (1, 2)
m2 = torch.Tensor([[3], [4]]) # (3,
                              #  4)

print(m1+m2) # (4, 5
             #  5, 6)
print(m1*m2) # (3, 6
             #  4, 8)
print(m1.mul(m2)) # (3, 6
                  #  4, 8)
print(m1.matmul(m2)) # (11)

tensor([[4., 5.],
        [5., 6.]])
tensor([[3., 6.],
        [4., 8.]])
tensor([[3., 6.],
        [4., 8.]])
tensor([[11.]])


### 3. mean(sum)

In [8]:
"""
t = (1, 2
     3, 4)

t.mean() == (1+2+3+4)/4 == 2.5
t.mean(dim=0) == [(1+3)/2, (2+4)/2] == [2, 3]
t.mean(dim=1) == ((1+2)/2,  ==  (1.5,  ==> [1.5, 3.5]
                  (3+4)/2)       3.5)
"""
import torch
t = torch.Tensor([[1, 2], [3, 4]]) # (1, 2
                                   #  3, 4)

print(t.mean()) # 2.5
print(t.mean(dim=0)) # [2, 3]
print(t.mean(dim=1)) # [1.5, 3.5]

print(t.sum()) # 10
print(t.sum(dim=0)) # [4, 6]
print(t.sum(dim=1)) # [3, 7]

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor(10.)
tensor([4., 6.])
tensor([3., 7.])


### 4. max, argmax

In [12]:
"""
max == maximum value, argmax = maximum value's index
t = (1, 2
     3, 4)

t.max() == max(1, 2, 3, 4) == 4

t.max(dim=0) == (values=[3, 4], indices=[1, 1])
t.max(dim=0)[0] == [max(1, 3), max(2, 4)] == [3, 4]
t.max(dim=0)[1] == [argmax(1, 3), max(2, 4)] == [1, 1]

t.max(dim=1) == (values=[2, 4], indices=[1, 1])
t.max(dim=1)[0] == (max(1, 2),  ==  (2,  == [2, 4]
                    max(3, 4))       4)
t.max(dim=1)[1] == (argmax(1, 2),  ==  (1,  == [1, 1]
                    argmax(3, 4))       1)                   

"""
import torch
t = torch.Tensor([[1, 2], [3, 4]]) # (1, 2
                                   #  3, 4)

print(t.max()) # 4

print(t.max(dim=0)) # (values=[3, 4], indices=[1, 1])
print(t.max(dim=0)[0]) # [3, 4]
print(t.max(dim=0)[1]) # [1, 1]

print(t.max(dim=1)) # (values=[2, 4], indices=[1, 1])
print(t.max(dim=1)[0]) # [2, 4]
print(t.max(dim=1)[1]) # [1, 1]


tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
tensor([3., 4.])
tensor([1, 1])
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
tensor([2., 4.])
tensor([1, 1])


### 5. view

In [17]:
"""
reshape tensor like np.reshape
t = ( (0, 1, 2,  (6, 7, 8
       3, 4, 5),  9, 10, 11) )
t.shape == [2, 2, 3]

t.view([-1, 3]) == (0, 1, 2,
                    3, 4, 5,
                    6, 7, 8,
                    9, 10, 11)
t.view([-1, 3]).shape == [4, 3]

t.view([-1, 1, 3]) == ( (0, 1, 2), (3, 4, 5), (6, 7, 8), (9, 10, 11) )
t.view([-1, 1, 3]).shape == [4, 1, 3]
"""

import torch
t = torch.Tensor([[[0, 1, 2], [3, 4, 5]],  # ( (0, 1, 2,  (6, 7, 8
                   [[6, 7, 8], [9, 10, 11]]]) # 3, 4, 5),  9, 10, 11) )

print(t.shape) # [2, 2, 3]
print(t.view([-1, 3])) # (0, 1, 2,
                       #  3, 4, 5,
                       #  6, 7, 8,
                       #  9, 10, 11)
print(t.view([-1, 3]).shape) # [4, 3]

print(t.view([-1, 1, 3])) # ( (0, 1, 2), (3, 4, 5), (6, 7, 8), (9, 10, 11) )
print(t.view([-1, 1, 3]).shape) # [4, 1, 3]


torch.Size([2, 2, 3])
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])
tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


### 6. squeeze, unsqueeze

In [19]:
"""
"squeeze"
t = (1,
     2)
t.shape == [2, 1]

t.squeeze() == [1, 2]
t.squeeze().shape == [2]

"unsqeeze"
t = [1, 2]
t.shape == [2]

t.unsqueeze(0) == (1, 2)
t.unsqueeze(0).shape == [1, 2]
t.unsqueeze(1) == (1,
                   2)
t.unsqueeze(1).shape == [2, 1]
"""
# squeeze
import torch
t = torch.Tensor([[1], [2]]) # (1,
                             #  2)
print(t.shape) # [2, 1]
print(t.squeeze()) # [1, 2]
print(t.squeeze().shape) # [2]

# unsqueeze
t = torch.Tensor([1, 2]) # [1, 2]
print(t.shape) # [2]
print(t.unsqueeze(0)) # (1, 2)
print(t.unsqueeze(0).shape) # [1, 2]
print(t.unsqueeze(1)) # (1,
                      #  2)
print(t.unsqueeze(1).shape) # [2, 1]

torch.Size([2, 1])
tensor([1., 2.])
torch.Size([2])
torch.Size([2])
tensor([[1., 2.]])
torch.Size([1, 2])
tensor([[1.],
        [2.]])
torch.Size([2, 1])


### 7. type casting

In [21]:
"""
torch.Tensor == torch.FloatTensor

t = torch.Tensor([1, 2])
t.type() == torch.FloatTensor
t.long().type() == torch.LongTensor
t.byte().type() == torch.ByteTensor
"""
import torch
t = torch.Tensor([1, 2])
print(t.type()) # torch.FloatTensor
print(t.long().type()) # torch.LongTensor
print(t.byte().type()) # torch.ByteTensor

torch.FloatTensor
torch.LongTensor
torch.ByteTensor


### 8. concatenate, stacking

In [25]:
"""
t1 = (1, 2,    t2 = (7, 8,
      3, 4,            9, 10,
      5, 6)            11, 12)

"concatenate"
torch.cat([t1, t2], dim=0) == (1, 2,
                               3, 4,
                               5, 6,
                               7, 8,
                               9, 10,
                               11, 12)
torch.cat([t1, t2], dim=0).shape == [6,2]
torch.cat([t1, t2], dim=1) == (1, 2, 7, 8,
                               3, 4, 9, 10,
                               5, 6, 11, 12)
torch.cat([t1, t2], dim=1).shape == [3, 4]

"stacking"
torch.stack([t1, t2], dim=0)) == ( (1, 2,  (7, 8,
                                    3, 4,   9, 10,
                                    5, 6),  11, 12) )
torch.stack([t1, t2], dim=0)).shape == [2, 3, 2]
torch.stack([t1, t2], dim=1)) == ( (1, 2,   (3, 4,   (5, 6
                                    7, 8),  9, 10), 11, 12) )
torch.stack([t1, t2], dim=0)).shape == [3, 2, 2]                              
"""
import torch
t1 = torch.Tensor([[1, 2], [3, 4], [5, 6]]) # (1, 2,
                                            #  3, 4,
                                            #  5, 6)
t2 = torch.Tensor([[7, 8], [9, 10], [11, 12]]) # (7, 8,
                                               #  9, 10,
                                               #  11, 12)

print(torch.cat([t1, t2], dim=0)) # (1, 2,
                                  #  3, 4,
                                  #  5, 6,
                                  #  7, 8,
                                  #  9, 10,
                                  #  11, 12)
print(torch.cat([t1, t2], dim=0).shape) # [6, 2]
print(torch.cat([t1, t2], dim=1)) # (1, 2, 7, 8
                                  #  3, 4, 9, 10,
                                  #  5, 6, 11, 12)
print(torch.cat([t1, t2], dim=1).shape) # [3, 4]

print(torch.stack([t1, t2], dim=0)) # ( (1, 2,  (7, 8,
                                    #    3, 4,   9, 10,
                                    #    5, 6),  11, 12) )
print(torch.stack([t1, t2], dim=0).shape) # [2, 3, 2]
print(torch.stack([t1, t2], dim=1)) # ( (1, 2,   (3, 4,   (5, 6
                                    #    7, 8),  9, 10), 11, 12) )
print(torch.stack([t1, t2], dim=1).shape) # [3, 2, 2]

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [11., 12.]])
torch.Size([6, 2])
tensor([[ 1.,  2.,  7.,  8.],
        [ 3.,  4.,  9., 10.],
        [ 5.,  6., 11., 12.]])
torch.Size([3, 4])
tensor([[[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.]],

        [[ 7.,  8.],
         [ 9., 10.],
         [11., 12.]]])
torch.Size([2, 3, 2])
tensor([[[ 1.,  2.],
         [ 7.,  8.]],

        [[ 3.,  4.],
         [ 9., 10.]],

        [[ 5.,  6.],
         [11., 12.]]])
torch.Size([3, 2, 2])
tensor([[[ 1.,  7.],
         [ 2.,  8.]],

        [[ 3.,  9.],
         [ 4., 10.]],

        [[ 5., 11.],
         [ 6., 12.]]])


### 9. ones and zeros like

In [26]:
"""
t = (1, 2
     3, 4)
torch.ones_like(t) == (1, 1
                       1, 1)
torch.zeros_like(t) == (0, 0
                        0, 0)
"""
import torch
t = torch.Tensor([[1, 2], [3, 4]]) # (1, 2
                                   #  3, 4)
print(torch.ones_like(t)) # (1, 1
                          #  1, 1)
print(torch.zeros_like(t)) # (0, 0
                           #  0, 0)


tensor([[1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.]])


### 10. zip

In [27]:
for i, j in zip([1, 2, 3], [4, 5, 6]):
    print(i, j) # 1 4
                # 2 5
                # 3 6

1 4
2 5
3 6
