In [10]:
# mothod 1.
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(777)

x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6,2]]
y_data = [[0], [0], [0], [1], [1], [1]]
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

W = torch.zeros((2, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

optimizer = optim.SGD([W, b], lr=1)

nb_epochs = 100
for epoch in range(1, nb_epochs+1):
    # hypothesis = 1 / (1 + torch.exp(-(x_train.matmul(W) + b)))
    hypothesis = torch.sigmoid(x_train.matmul(W) + b)

    # losses = -(y_train * torch.log(hypothesis) + (1 - y_train) * torch.log(1 - hypothesis))
    # cost = losses.mean()
    cost = F.binary_cross_entropy(hypothesis, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 10 == 0:
        print(f'epochs: {epoch}/{nb_epochs}, cost: {cost.item()}')

torch.set_printoptions(sci_mode=False)
hypothesis = torch.sigmoid(x_train.matmul(W) + b)
print(hypothesis)
prediction = (hypothesis >= 0.5).type(torch.FloatTensor)
print(prediction)
correct_prediction = prediction == y_train
print(correct_prediction)

epochs: 10/100, cost: 0.4955716133117676
epochs: 20/100, cost: 0.45466527342796326
epochs: 30/100, cost: 0.38243213295936584
epochs: 40/100, cost: 0.3243464231491089
epochs: 50/100, cost: 0.2732938230037689
epochs: 60/100, cost: 0.22697977721691132
epochs: 70/100, cost: 0.18711109459400177
epochs: 80/100, cost: 0.16004030406475067
epochs: 90/100, cost: 0.14572511613368988
epochs: 100/100, cost: 0.13564400374889374
tensor([[0.0245],
        [0.1484],
        [0.2770],
        [0.7954],
        [0.9484],
        [0.9834]], grad_fn=<SigmoidBackward>)
tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.]])
tensor([[True],
        [True],
        [True],
        [True],
        [True],
        [True]])


In [7]:
# method 2.
class BinaryClassifier(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(2, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        return self.sigmoid(self.linear(x))

model = BinaryClassifier()
optimizer = optim.SGD(model.parameters(), lr=1)

nb_epochs = 100
for epoch in range(1, nb_epochs+1):
    hypothesis = model(x_train)

    cost = F.binary_cross_entropy(hypothesis, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 10 == 0:
        print(f'epochs: {epoch}/{nb_epochs}, cost: {cost.item()}')

torch.set_printoptions(sci_mode=False)
hypothesis = model(x_train)
print(hypothesis)
prediction = (hypothesis >= 0.5).type(torch.FloatTensor)
print(prediction)
correct_prediction = prediction.float() == y_train
print(correct_prediction)

epochs: 10/100, cost: 1.0310767889022827
epochs: 20/100, cost: 0.6099081635475159
epochs: 30/100, cost: 0.507769763469696
epochs: 40/100, cost: 0.42099571228027344
epochs: 50/100, cost: 0.33837273716926575
epochs: 60/100, cost: 0.26213324069976807
epochs: 70/100, cost: 0.20035725831985474
epochs: 80/100, cost: 0.16357332468032837
epochs: 90/100, cost: 0.14729078114032745
epochs: 100/100, cost: 0.13692478835582733
tensor([[0.0249],
        [0.1484],
        [0.2790],
        [0.7932],
        [0.9473],
        [0.9831]], grad_fn=<SigmoidBackward>)
tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.]])
tensor([[True],
        [True],
        [True],
        [True],
        [True],
        [True]])
