In [3]:
# package import
import torch

### * 1D Array with pytorch

In [47]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print('* 1D Array with pytorch')
print(f't: {t}')
print(f't.dim(): \t {t.dim()}')
print(f't.size(): \t {t.size()}')
print(f't[1:-1]: {t[1:-1]}')


* 1D Array with pytorch
t: tensor([0., 1., 2., 3., 4., 5., 6.])
t.dim(): 	 1
t.size(): 	 torch.Size([7])
t[1:-1]: tensor([1., 2., 3., 4., 5.])


### * 2D Array with pytorch

In [48]:
print('* 2D Array with pytorch')
t1 = torch.FloatTensor([[1,2]])
t2 = torch.FloatTensor([[1],[2]])
print(f't1: {t1}')
print(f't2: {t2} \n')

t = torch.FloatTensor([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(f't: {t}')
print(f't.dim(): \t {t.dim()}')
print(f't.size(): \t {t.size()}')
print(f't[:,1]: {t[:,1]}')
print(f't[:,1].size(): \t {t[:,1].size()}')
print(f't[:, :-1]: {t[:, :-1]}')

* 2D Array with pytorch
t1: tensor([[1., 2.]])
t2: tensor([[1.],
        [2.]]) 

t: tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
t.dim(): 	 2
t.size(): 	 torch.Size([4, 3])
t[:,1]: tensor([ 2.,  5.,  8., 11.])
t[:,1].size(): 	 torch.Size([4])
t[:, :-1]: tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


### * Broadcasting

In [49]:
print('* Broadcasting')

# same shape
print('** vector + vector (same shape)')
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(f'm1: {m1}')
print(f'm2: {m2}')
print(f'm1+m2: {m1+m2} \n')

# vector + scalar
print('** vector + scalar')
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([3]) # 3 -> [[3,3]]
print(f'm1: {m1}')
print(f'm2: {m2}')
print(f'm1+m2: {m1+m2} \n')

# vector + vector (different shape)
print('** vector + vector (different shape)')
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3],[4]])
print(f'm1: {m1}')
print(f'm2: {m2}')
print(f'm1+m2(): {m1+m2} \n')

* Broadcasting
** vector + vector (same shape)
m1: tensor([[3., 3.]])
m2: tensor([[2., 2.]])
m1+m2: tensor([[5., 5.]]) 

** vector + scalar
m1: tensor([[1., 2.]])
m2: tensor([3.])
m1+m2: tensor([[4., 5.]]) 

** vector + vector (different shape)
m1: tensor([[1., 2.]])
m2: tensor([[3.],
        [4.]])
m1+m2(): tensor([[4., 5.],
        [5., 6.]]) 



In [51]:
# vector * vector
print('** vector * vector')
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print(f'm1: {m1}')
print(f'm2: {m2} \n')
print(f'*** matrix multification (m1.matmul(m2)) \n {m1.matmul(m2)} \n')
print(f'*** element wise multification (m1 * m2) \n {m1 * m2} \n')
print(f'*** element wise multification (m1.mul(m2)) \n {m1.mul(m2)} \n')

** vector * vector
m1: tensor([[1., 2.],
        [3., 4.]])
m2: tensor([[1.],
        [2.]]) 

*** matrix multification (m1.matmul(m2)) 
 tensor([[ 5.],
        [11.]]) 

*** element wise multification (m1 * m2) 
 tensor([[1., 2.],
        [6., 8.]]) 

*** element wise multification (m1.mul(m2)) 
 tensor([[1., 2.],
        [6., 8.]]) 



### * mean

In [55]:
print('* mean (sum)')

t = torch.FloatTensor([1, 2])
print('** 1D array mean()')
print(f't: {t}')
print(f't.mean(): \t {t.mean()} \n')

print('** 2D array mean()')
t = torch.FloatTensor([[1, 2], [3, 4]])
print(f't: {t}')
print(f't.mean(): \t {t.mean()}')
print(f't.mean(dim=0): \t {t.mean(dim=0)}')
print(f't.mean(dim=1): \t {t.mean(dim=1)}')
print(f't.mean(dim=-1): \t {t.mean(dim=-1)}')


* mean (sum)
** 1D array mean()
t: tensor([1., 2.])
t.mean(): 	 1.5 

** 2D array mean()
t: tensor([[1., 2.],
        [3., 4.]])
t.mean(): 	 2.5
t.mean(dim=0): 	 tensor([2., 3.])
t.mean(dim=1): 	 tensor([1.5000, 3.5000])
t.mean(dim=-1): 	 tensor([1.5000, 3.5000])


### * max, argmax

In [61]:
print('* max, argmax')

t = torch.FloatTensor([[3, 2], [1, 4]])
print(f't: {t}')
print(f't.max(): \t {t.max()} \n')

print(f't.max(dim=0): \n {t.max(dim=0)} \n')

print(f't.max(dim=0)[0]: \t {t.max(dim=0)[0]}')
print(f't.max(dim=0)[1]: \t {t.max(dim=0)[1]} \n')

print(f't.max(dim=1): \n {t.max(dim=1)}')

* max, argmax
t: tensor([[3., 2.],
        [1., 4.]])
t.max(): 	 4.0 

t.max(dim=0): 
 torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([0, 1])) 

t.max(dim=0)[0]: 	 tensor([3., 4.])
t.max(dim=0)[1]: 	 tensor([0, 1]) 

t.max(dim=1): 
 torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([0, 1]))


### * view (reshape)

In [65]:
import numpy as np
print(f'* view (reshape)')

t = np.array([[[0, 1, 2],
               [3, 4, 5]],
               
              [[6, 7, 8],
               [9, 10, 11]]])
t = torch.FloatTensor(t)
print(f't: \n {t}')
print(f't.size(): \t {t.size()} \n')

print(f't.view([-1, 3]): \n {t.view([-1, 3])}')
print(f't.view([-1, 3]).size(): \t {t.view([-1, 3]).size()} \n')

print(f't.view([-1, 1, 3]): \n {t.view([-1, 1, 3])}')
print(f't.view([-1, 1, 3]).size(): \t {t.view([-1, 1, 3]).size()} \n')

* view (reshape)
t: 
 tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])
t.size(): 	 torch.Size([2, 2, 3]) 

t.view([-1, 3]): 
 tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
t.view([-1, 3]).size(): 	 torch.Size([4, 3]) 

t.view([-1, 1, 3]): 
 tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
t.view([-1, 1, 3]).size(): 	 torch.Size([4, 1, 3]) 



### * squeeze

In [70]:
print(f'* squeeze')

t = torch.FloatTensor([[0], [1], [2]])
print(f't: \n {t}')
print(f't.size(): \t {t.size()} \n')

print(f't.squeeze(): {t.squeeze()}')
print(f't.squeeze().size(): \t {t.squeeze().size()}')

* squeeze
t: 
 tensor([[0.],
        [1.],
        [2.]])
t.size(): 	 torch.Size([3, 1]) 

t.squeeze(): tensor([0., 1., 2.])
t.squeeze().size(): 	 torch.Size([3])


### * unsqueeze

In [78]:
print('* unsqueeze')

t = torch.Tensor([0, 1, 2])
print(f't: {t}')
print(f't.size(): {t.size()} \n')

print(f't.unsqueeze(0): {t.unsqueeze(0)}')
print(f't.unsqueeze(0).size(): \t {t.unsqueeze(0).size()}')
print(f't.view(1, -1): {t.view(1, -1)}')
print(f't.view(1, -1).size(): \t {t.view(1, -1).size()} \n')

print(f't.unsqueeze(1): \n {t.unsqueeze(1)}')
print(f't.unsqueeze(1).size(): \t {t.unsqueeze(1).size()}')
print(f't.unsqueeze(-1): \n {t.unsqueeze(-1)}')
print(f't.unsqueeze(-1).size(): \t {t.unsqueeze(-1).size()}')


* unsqueeze
t: tensor([0., 1., 2.])
t.size(): torch.Size([3]) 

t.unsqueeze(0): tensor([[0., 1., 2.]])
t.unsqueeze(0).size(): 	 torch.Size([1, 3])
t.view(1, -1): tensor([[0., 1., 2.]])
t.view(1, -1).size(): 	 torch.Size([1, 3]) 

t.unsqueeze(1): 
 tensor([[0.],
        [1.],
        [2.]])
t.unsqueeze(1).size(): 	 torch.Size([3, 1])
t.unsqueeze(-1): 
 tensor([[0.],
        [1.],
        [2.]])
t.unsqueeze(-1).size(): 	 torch.Size([3, 1])


In [80]:
t = torch.Tensor([[0, 1, 2],
                  [3, 4, 5]])
print(f't: {t}')
print(f't.size(): {t.size()} \n')

print(f't.unsqueeze(0): \n {t.unsqueeze(0)}')
print(f't.unsqueeze(0).size(): \t {t.unsqueeze(0).size()}')
print(f't.view(1, -1): {t.view(1, -1)}')
print(f't.view(1, -1).size(): \t {t.view(1, -1).size()} \n')

print(f't.unsqueeze(1): \n {t.unsqueeze(1)}')
print(f't.unsqueeze(1).size(): \t {t.unsqueeze(1).size()}')
print(f't.unsqueeze(-1): \n {t.unsqueeze(-1)}')
print(f't.unsqueeze(-1).size(): \t {t.unsqueeze(-1).size()}')

t: tensor([[0., 1., 2.],
        [3., 4., 5.]])
t.size(): torch.Size([2, 3]) 

t.unsqueeze(0): 
 tensor([[[0., 1., 2.],
         [3., 4., 5.]]])
t.unsqueeze(0).size(): 	 torch.Size([1, 2, 3])
t.view(1, -1): tensor([[0., 1., 2., 3., 4., 5.]])
t.view(1, -1).size(): 	 torch.Size([1, 6]) 

t.unsqueeze(1): 
 tensor([[[0., 1., 2.]],

        [[3., 4., 5.]]])
t.unsqueeze(1).size(): 	 torch.Size([2, 1, 3])
t.unsqueeze(-1): 
 tensor([[[0.],
         [1.],
         [2.]],

        [[3.],
         [4.],
         [5.]]])
t.unsqueeze(-1).size(): 	 torch.Size([2, 3, 1])


### * type casting

In [85]:
print('* type casting')

lt = torch.LongTensor([1, 2, 3, 4])
print(f'lt: {lt}')
print(f'lt.type(): {lt.type()}')
print(f'lt.float(): {lt.float()}')
print(f'lt.float().type(): {lt.float().type()} \n')

bt = torch.ByteTensor([True, False, False, True])
print(f'bt: {bt}')
print(f'bt.type(): {bt.type()}')
print(f'bt.long(): {bt.long()}')
print(f'bt.long().type(): {bt.float().long()}')
print(f'bt.float(): {bt.float()}')
print(f'bt.float().type(): {bt.float().type()} \n')


* type casting
lt: tensor([1, 2, 3, 4])
lt.type(): torch.LongTensor
lt.float(): tensor([1., 2., 3., 4.])
lt.float().type(): torch.FloatTensor 

bt: tensor([1, 0, 0, 1], dtype=torch.uint8)
bt.type(): torch.ByteTensor
bt.long(): tensor([1, 0, 0, 1])
bt.long().type(): tensor([1, 0, 0, 1])
bt.float(): tensor([1., 0., 0., 1.])
bt.float().type(): torch.FloatTensor 



### * scatter for one-hot

In [97]:
print('* scatter for one-hot')

t = torch.LongTensor([[0], [1], [2], [0]])
print(f't: \n {t} \n')

one_hot = torch.zeros(4, 3)
print(f'one_hot: \n {one_hot}')

print(f'one_hot.scatter_(1, t, 1): \n {one_hot.scatter_(1, t, 1)}')

* scatter for one-hot
t: 
 tensor([[0],
        [1],
        [2],
        [0]]) 

one_hot: 
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
one_hot.scatter_(1, t, 1): 
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]])


### * concatenate

In [87]:
print('* concatenate')
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])
print(f'x: \n {x}')
print(f'y: \n {y} \n')

print(f'torch.cat([x, y], dim=0: \n {torch.cat([x, y], dim=0)}')
print(f'torch.cat([x, y], dim=1: \n {torch.cat([x, y], dim=1)}')

* concatenate
x: 
 tensor([[1., 2.],
        [3., 4.]])
y: 
 tensor([[5., 6.],
        [7., 8.]]) 

torch.cat([x, y], dim=0: 
 tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
torch.cat([x, y], dim=1: 
 tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


### * stacking

In [89]:
print('* stacking')
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

print(f'x: {x}')
print(f'y: {y}')
print(f'z: {z} \n')

print(f'torch.stack([x,y,z]): \n {torch.stack([x,y,z])}')
print(f'torch.stack([x,y,z], dim=-1): \n {torch.stack([x,y,z], dim=-1)} \n')

print(f'torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0): \n {torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0)}')



* stacking
x: tensor([1., 4.])
y: tensor([2., 5.])
z: tensor([3., 6.]) 

torch.stack([x,y,z]): 
 tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
torch.stack([x,y,z], dim=-1): 
 tensor([[1., 2., 3.],
        [4., 5., 6.]]) 

torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0): 
 tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


### * ones and zeros like

In [91]:
print('* ones and zeros like')
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(f'x: \n {x}')
print(f'torch.ones_like(x): \n {torch.ones_like(x)}')
print(f'torch.zeros_like(x): \n {torch.zeros_like(x)}')

* ones and zeros like
x: 
 tensor([[0., 1., 2.],
        [2., 1., 0.]])
torch.ones_like(x): 
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
torch.zeros_like(x): 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


### * zip

In [99]:
print('* zip')
for i, j in zip([1, 2, 3], [4, 5, 6]):
    print(i,j)

* zip
1 4
2 5
3 6
